### ISSUE TITLE
您好，请问您是知乎上面那个知乎编程组的00后吗？？

### ISSUE THREAD

**Issue by zunsthy** [yh200212121212/KindleHelper#1]
Exciting !

**Comment by yh200212121212** [comment]
是的

**Comment by ice1000** [comment]
是的，这就是大佬的仓库啊，35mb

**Comment by singleNeuron** [comment]
震惊：知乎小学生在一次采访中无意暴露了他的GitHub地址，来晚了他就要删档跑路了。

**Comment by ice1000** [comment]
35MB

**Comment by yh200212121212** [comment]
So?I can download it.

**Comment by yh200212121212** [comment]
@ice1000

**Comment by ice1000** [comment]
Wtf
You can download it but who cares

**Comment by ice1000** [comment]
Anybody want to clone your target files

**Comment by yh200212121212** [comment]
> Anybody want to clone your target files

So,everybody can't clone now,can they?

> Wtf
You can download it but who cares

So??

**Comment by zccz14** [comment]
前来围观

**Comment by liuziangexit** [comment]
stay young, stay naive

**Comment by thautwarm** [comment]
愉悦

**Comment by yh200212121212** [comment]
真是悲哀

**Comment by liuziangexit** [comment]
真是悲哀

**Comment by ice1000** [comment]
:trollface:

**Comment by yh200212121212** [comment]
。。。。
求继续当朋友 @ice1000

**Comment by liuziangexit** [comment]
继续当朋友

**Comment by ice1000** [comment]
来啊 https://github.com/Cm-lang/Cmc

**Comment by yh200212121212** [comment]
来啊各位https://github.com/KindleHelper

**Comment by ice1000** [comment]
不  太大了不想clone

**Comment by ice1000** [comment]
md我要把你block了

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/30442899-6861b782-99b0-11e7-9a1e-b27e371da549.png)
再见 鲨鱼啦啦

**Comment by yh200212121212** [comment]
诶……

**Comment by yh200212121212** [comment]
如今已经3mb了

**Comment by liuziangexit** [comment]
是因为里面带的二进制么呵呵，毕竟是gitignore也不会写的小朋友

**Comment by yh200212121212** [comment]
然而并不是
